### ISSUE TITLE
Allow name, uuid or object as argument for parameters

### ISSUE THREAD

**Issue by ctx** [cloudscale-ch/ansible-collection-cloudscale#56]
Some users might want to use fixed names for their resources in their playbooks:
```
    - name: Create volume
      cloudscale_ch.cloud.volume:
        name: 'my_ssd_volume'
        ...

    - name: Start a server
      cloudscale_ch.cloud.server:
        name: 'my_server'
        ...

    - name: Attach volume to server
      cloudscale_ch.cloud.volume:
        name: 'my_ssd_volume'
        servers:
          - 'my_server'
```

Other users don't want to dig into the structure of return values to pass a uuid to another task:
```
    - name: Create volume
      cloudscale_ch.cloud.volume:
        name: my_ssd_volume
        ...
      register: volume

    - name: Start a server
      cloudscale_ch.cloud.server:
        name: my_server
        ...
      register: server

    - name: Attach volume to server
      cloudscale_ch.cloud.volume:
        name: "{{ volume }}"
        servers:
          - "{{ server }}"
```

Create a function that can compare `uuid`, `name` or an `object` with a given `object`.

Spot all parameters that take only `name`, `uuid` or an `object` and make it possible to use any.
